# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161017_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': (('can_bypass_location_check', 'Can bypass location check'), ('can_bypass_age_check', 'Can bypass age check'), ('can_bypass_identity_verification', 'Can bypass identity verification'), ('email_confirmation', 'Email confirmation')), 'verbose_name': 'Information', 'verbose_name_plural': 'information'},
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'Country check failed'), (1, 'State check failed'), (2, 'VPN check failed'), (3, 'IP check status'), (4, 'IP check bypassed, user on local network'), (5, 'User Login'), (6, 'Lineup creation'), (7, 'Lineup edited'), (8, 'Contest entered'), (9, 'Contest deregistered'), (10, 'Deposit funds'), (11, 'Deposit pageview'), (12, 'Withdraw request - paypal'), (13, 'Trulioo verification failed'), (14, 'Trulioo verification success'), (15, 'User identity is already claimed'), (16, 'IP not found in the db')]),
        ),
    ]
