# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 13:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20160627_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'IP check result'), (1, 'Country check result'), (2, 'State check result')])),
                ('ip', models.CharField(max_length=15)),
                ('action', models.SmallIntegerField(choices=[(0, 'User Login'), (1, 'Line up creation'), (2, 'Contest join'), (3, 'Deposit money')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'User Logs',
                'verbose_name': 'User Log',
            },
        ),
    ]
