# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161017_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='exclude_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
