# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161207_1720'),
        ('account', '0003_information_exclude_date'),
    ]

    operations = [
    ]
