# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'Deposit Limit'), (1, 'Contest Entry Alert'), (2, 'Contest Entry Limit'), (3, 'Entry Fee Limit')])),
                ('value', models.IntegerField(blank=True, choices=[(50, '$50'), (100, '$100'), (250, '$250'), (500, '$500'), (750, '$750'), (1000, '$1000'), (25, '25'), (50, '50'), (100, '100')])),
                ('time_period', models.SmallIntegerField(blank=True, choices=[(30, 'Monthly'), (7, 'Weekly'), (1, 'Daily')], null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
