# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161213_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='time_period',
            field=models.SmallIntegerField(blank=True, choices=[(30, 'Monthly'), (7, 'Weekly'), (1, 'Daily')], null=True),
        ),
        migrations.AlterField(
            model_name='limit',
            name='value',
            field=models.IntegerField(blank=True),
        ),
    ]
