# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_merge'),
        ('account', '0003_auto_20161207_1314'),
    ]

    operations = [
    ]
