# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-06 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identity', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
