# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170106_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
