# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_identity_flagged'),
        ('account', '0004_limit'),
    ]

    operations = [
    ]
