# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20161026_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': (('can_bypass_location_check', 'Can bypass location check'), ('can_bypass_age_check', 'Can bypass age check'), ('can_bypass_identity_verification', 'Can bypass identity verification')), 'verbose_name': 'Information', 'verbose_name_plural': 'information'},
        ),
        migrations.RemoveField(
            model_name='information',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='information',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='information',
            name='city',
        ),
        migrations.RemoveField(
            model_name='information',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='information',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='information',
            name='state',
        ),
        migrations.RemoveField(
            model_name='information',
            name='zipcode',
        ),
    ]
