# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 00:29
from __future__ import unicode_literals

from django.db import migrations


def create_information_model_for_all_users(apps, schema_editor):
    """
    We repurposed the Information model and it NEEDS to exist on a user now.
    This will make sure all users have an Information model attached to them.
    New users will get one upon registration.
    """

    User = apps.get_model('auth', 'User')
    Information = apps.get_model("account", "Information")

    for user in User.objects.all():
        print('Getting or creating Information model for user: %s' % user.username)
        Information.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20161028_0028'),
    ]

    operations = [
        migrations.RunPython(create_information_model_for_all_users),
    ]
