# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170303_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'permissions': (('can_bypass_location_check', 'Can bypass location check'), ('can_bypass_age_check', 'Can bypass age check'), ('can_bypass_identity_verification', 'Can bypass identity verification')), 'verbose_name': 'Information', 'verbose_name_plural': 'information'},
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
