# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170321_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Location verification'), (1, 'Contest actions'), (2, 'User funds actions'), (3, 'User authentication')]),
        ),
    ]
