# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170703_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='status',
            field=models.BooleanField(default=False, help_text="Is the customer's identity verified?"),
        ),
    ]
