# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170716_2111'),
        ('account', '0012_identity_status'),
    ]

    operations = [
    ]
