# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_merge_20170717_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='has_created_a_lineup',
            field=models.BooleanField(default=False),
        ),
    ]
