# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_block_contest_pools_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdcontest',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='createdcontest',
            name='scheduled_template_contest',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='site_sport',
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtemplatecontest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='scheduledtemplatecontest',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='scheduledtemplatecontest',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduledtemplatecontest',
            name='template_contest',
        ),
        migrations.RemoveField(
            model_name='templatecontest',
            name='draft_group',
        ),
        migrations.RemoveField(
            model_name='templatecontest',
            name='prize_structure',
        ),
        migrations.RemoveField(
            model_name='templatecontest',
            name='site_sport',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CreatedContest',
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduledTemplateContest',
        ),
        migrations.DeleteModel(
            name='TemplateContest',
        ),
    ]
