# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20160719_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
