# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20170821_1819'),
        ('schedule', '0010_auto_20170814_2203'),
    ]

    operations = [
    ]
