# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0004_auto_20170303_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpp',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='rake',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
    ]
