instrumentation:
    root: ./static/src/js/
    extensions: ['.jsx', '.js']
    excludes: ['**fixtures/**', 'app.jsx', 'app-logged-out.jsx']

# hooks:
#     post-require-hook: null
#     hook-run-in-context: true
