# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swish', '0002_history_playerlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerlookup',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playerlookup',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='playerlookup',
            name='player_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerlookup',
            name='player_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swish_playerlookup_player_lookup', to='contenttypes.ContentType'),
        ),
    ]
