# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('statscom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player_id', models.PositiveIntegerField()),
                ('pid', models.CharField(max_length=255)),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statscom_playerlookup_player_lookup', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
