# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20170301_2008'),
        ('buyin', '0003_auto_20170301_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyin',
            name='contest_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.ContestPool'),
        ),
    ]
