# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax', '0002_auto_20150422_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm1099',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('sent', models.BooleanField(default=False)),
                ('net_profit', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taxform1099',
            unique_together=set([('user', 'year')]),
        ),
    ]
