# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.utils.timezone import utc
import datetime


class Migration(migrations.Migration):

    replaces = [('mlb', '0001_initial'), ('mlb', '0002_auto_20150528_2321'), ('mlb', '0003_auto_20150625_0016'), ('mlb', '0004_game_prev_status'), ('mlb', '0005_tsxinjury_tsxnews_tsxplayer_tsxteam_tsxtransaction'), ('mlb', '0006_auto_20160110_2114'), ('mlb', '0007_auto_20160110_2243'), ('mlb', '0008_player_season_fppg'), ('mlb', '0009_auto_20160119_2126')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sports', '0001_squashed_0008_auto_20160119_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', max_length=64, unique=True)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('srid_home', models.CharField(max_length=64, help_text='home team sportsradar global id')),
                ('srid_away', models.CharField(max_length=64, help_text='away team sportsradar global id')),
                ('title', models.CharField(null=True, max_length=128)),
                ('attendance', models.IntegerField(default=0)),
                ('day_night', models.CharField(default='', max_length=8)),
                ('game_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameBoxscore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(default=None, max_length=64, unique=True, help_text='the sportsradar global id for the game')),
                ('srid_home', models.CharField(max_length=64)),
                ('srid_away', models.CharField(max_length=64)),
                ('home_id', models.PositiveIntegerField()),
                ('away_id', models.PositiveIntegerField()),
                ('attendance', models.IntegerField(default=0)),
                ('coverage', models.CharField(default='', max_length=16)),
                ('status', models.CharField(default='', max_length=64)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=256)),
                ('home_scoring_json', models.CharField(default='', max_length=2048)),
                ('away_scoring_json', models.CharField(default='', max_length=2048)),
                ('day_night', models.CharField(default='', max_length=8)),
                ('game_number', models.IntegerField(default=1)),
                ('inning', models.CharField(default='', max_length=16)),
                ('inning_half', models.CharField(default='', max_length=16)),
                ('srid_home_pp', models.CharField(null=True, max_length=64, help_text='srid of the HOME probable pitcher set before the game starts')),
                ('srid_home_sp', models.CharField(null=True, max_length=64, help_text='srid of the HOME starting pitcher')),
                ('srid_away_pp', models.CharField(null=True, max_length=64, help_text='srid of the AWAY probable pitcher set before the game starts')),
                ('srid_away_sp', models.CharField(null=True, max_length=64, help_text='srid of the AWAY starting pitcher')),
                ('srid_win', models.CharField(null=True, max_length=64)),
                ('srid_loss', models.CharField(null=True, max_length=64)),
                ('home_errors', models.IntegerField(default=0)),
                ('home_hits', models.IntegerField(default=0)),
                ('away_errors', models.IntegerField(default=0)),
                ('away_hits', models.IntegerField(default=0)),
                ('away_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_gameboxscore_away_team')),
                ('home_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_gameboxscore_home_team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePortion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game this is associate with')),
                ('game_id', models.PositiveIntegerField()),
                ('category', models.CharField(default='', max_length=32, help_text='typically one of these: ["inning-half","quarter","period"]')),
                ('sequence', models.IntegerField(default=0, help_text='an ordering of all GamePortions with the same srid_game')),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_gameportion_sport_game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('iid', models.CharField(help_text='custom injury id', max_length=128, unique=True)),
                ('player_id', models.PositiveIntegerField()),
                ('status', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=1024)),
                ('player_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_injury_injured_player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pbp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game')),
                ('game_id', models.PositiveIntegerField()),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_pbp_sport_game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PbpDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pbp_id', models.PositiveIntegerField()),
                ('portion_id', models.PositiveIntegerField()),
                ('idx', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1024)),
                ('pbp_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_pbpdescription_pbpdesc_pbp')),
                ('portion_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_pbpdescription_pbpdesc_portion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('injury_id', models.PositiveIntegerField(null=True)),
                ('srid_team', models.CharField(default='', max_length=64)),
                ('preferred_name', models.CharField(default='', max_length=64)),
                ('birthcity', models.CharField(default='', max_length=64)),
                ('birthcountry', models.CharField(default='', max_length=64)),
                ('birthdate', models.CharField(default='', max_length=64)),
                ('height', models.FloatField(default=0.0, help_text='inches')),
                ('weight', models.FloatField(default=0.0, help_text='lbs')),
                ('jersey_number', models.CharField(default='', max_length=64)),
                ('status', models.CharField(default='', max_length=64, help_text='roster status - ie: "A" means they are ON the roster. Not particularly active as in not-injured!')),
                ('pro_debut', models.CharField(default='', max_length=64)),
                ('throw_hand', models.CharField(default='', max_length=8)),
                ('bat_hand', models.CharField(default='', max_length=8)),
                ('injury_type', models.ForeignKey(null=True, to='contenttypes.ContentType', related_name='mlb_player_players_injury')),
                ('position', models.ForeignKey(to='sports.Position', related_name='mlb_player_player_position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsHitter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game')),
                ('srid_player', models.CharField(max_length=64, help_text='the sportsradar global id for the player')),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('bb', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('ktotal', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('ap', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('xbh', models.IntegerField(default=0)),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatshitter_sport_game')),
                ('player_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatshitter_sport_player')),
                ('position', models.ForeignKey(to='sports.Position', related_name='mlb_playerstatshitter_playerstats_position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsPitcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game')),
                ('srid_player', models.CharField(max_length=64, help_text='the sportsradar global id for the player')),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('ip_1', models.FloatField(default=0.0)),
                ('ip_2', models.FloatField(default=0.0)),
                ('ktotal', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('loss', models.BooleanField(default=False)),
                ('qstart', models.BooleanField(default=False)),
                ('er', models.IntegerField(default=0)),
                ('r_total', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('cg', models.BooleanField(default=False)),
                ('cgso', models.BooleanField(default=False)),
                ('nono', models.BooleanField(default=False)),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatspitcher_sport_game')),
                ('player_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatspitcher_sport_player')),
                ('position', models.ForeignKey(to='sports.Position', related_name='mlb_playerstatspitcher_playerstats_position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('start_year', models.CharField(max_length=100)),
                ('season_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', max_length=64, unique=True)),
                ('srid_venue', models.CharField(max_length=64, help_text='the sportsradar global id')),
                ('name', models.CharField(default='', max_length=64, help_text='the team name, without the market/city. ie: "Lakers", or "Eagles"')),
                ('alias', models.CharField(default='', max_length=64, help_text='the abbreviation for the team, ie: for Boston Celtic alias == "BOS"')),
                ('srid_league', models.CharField(max_length=64, help_text='league sportsradar id')),
                ('srid_division', models.CharField(max_length=64, help_text='division sportsradar id')),
                ('market', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(to='mlb.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(to='mlb.Team', related_name='game_awayteam'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(to='mlb.Team', related_name='game_hometeam'),
        ),
        migrations.AlterField(
            model_name='gameboxscore',
            name='coverage',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='game',
            name='prev_status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.CreateModel(
            name='TsxInjury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportradar global id for the item')),
                ('pcid', models.CharField(max_length=64, help_text='the providers content id for this item')),
                ('content_created', models.DateTimeField()),
                ('content_modified', models.DateTimeField()),
                ('content_published', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('byline', models.CharField(max_length=256)),
                ('dateline', models.CharField(max_length=32)),
                ('credit', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=8192)),
                ('tsxcontent', models.ForeignKey(to='sports.TsxContent', related_name='mlb_tsxinjury_tsxcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TsxNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportradar global id for the item')),
                ('pcid', models.CharField(max_length=64, help_text='the providers content id for this item')),
                ('content_created', models.DateTimeField()),
                ('content_modified', models.DateTimeField()),
                ('content_published', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('byline', models.CharField(max_length=256)),
                ('dateline', models.CharField(max_length=32)),
                ('credit', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=8192)),
                ('tsxcontent', models.ForeignKey(to='sports.TsxContent', related_name='mlb_tsxnews_tsxcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TsxPlayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('sportsdataid', models.CharField(max_length=64)),
                ('sportradarid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('tsxitem_id', models.PositiveIntegerField()),
                ('tsxitem_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_tsxplayer_tsxitem_tsxitemref')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TsxTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('sportsdataid', models.CharField(max_length=64)),
                ('sportradarid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('tsxitem_id', models.PositiveIntegerField()),
                ('tsxitem_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_tsxteam_tsxitem_tsxitemref')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TsxTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', auto_created=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportradar global id for the item')),
                ('pcid', models.CharField(max_length=64, help_text='the providers content id for this item')),
                ('content_created', models.DateTimeField()),
                ('content_modified', models.DateTimeField()),
                ('content_published', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('byline', models.CharField(max_length=256)),
                ('dateline', models.CharField(max_length=32)),
                ('credit', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=8192)),
                ('tsxcontent', models.ForeignKey(to='sports.TsxContent', related_name='mlb_tsxtransaction_tsxcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='injury',
            name='ddtimestamp',
            field=models.BigIntegerField(default=0, help_text='the time this injury update was parsed by dataden.this will be the same value for all objects that were in the feed on the last parse.'),
        ),
        migrations.AddField(
            model_name='tsxplayer',
            name='content_published',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 12, 0, tzinfo=utc), help_text='the item ref is a GFK so also store the publish date here for ordering purposes.'),
        ),
        migrations.AddField(
            model_name='tsxplayer',
            name='player',
            field=models.ForeignKey(default=None, to='mlb.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tsxteam',
            name='content_published',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 12, 0, tzinfo=utc), help_text='the item ref is a GFK so also store the publish date here for ordering purposes.'),
        ),
        migrations.AddField(
            model_name='tsxteam',
            name='team',
            field=models.ForeignKey(default=None, to='mlb.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tsxinjury',
            name='content',
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name='tsxnews',
            name='content',
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name='tsxtransaction',
            name='content',
            field=models.CharField(max_length=16384),
        ),
        migrations.AddField(
            model_name='player',
            name='season_fppg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 26, 16, 176028, tzinfo=utc), auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 26, 17, 112077, tzinfo=utc), auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstatshitter',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 26, 18, 31855, tzinfo=utc), auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstatspitcher',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 19, 2, 26, 19, 408245, tzinfo=utc), auto_now=True),
            preserve_default=False,
        ),
    ]
