# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sports', '0003_auto_20150528_2131'),
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', unique=True, max_length=64)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('srid_home', models.CharField(help_text='home team sportsradar global id', max_length=64)),
                ('srid_away', models.CharField(help_text='away team sportsradar global id', max_length=64)),
                ('title', models.CharField(null=True, max_length=128)),
                ('attendance', models.IntegerField(default=0)),
                ('day_night', models.CharField(default='', max_length=8)),
                ('game_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameBoxscore',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(help_text='the sportsradar global id for the game', default=None, unique=True, max_length=64)),
                ('srid_home', models.CharField(max_length=64)),
                ('srid_away', models.CharField(max_length=64)),
                ('home_id', models.PositiveIntegerField()),
                ('away_id', models.PositiveIntegerField()),
                ('attendance', models.IntegerField(default=0)),
                ('coverage', models.CharField(default='', max_length=16)),
                ('status', models.CharField(default='', max_length=64)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=256)),
                ('home_scoring_json', models.CharField(default='', max_length=2048)),
                ('away_scoring_json', models.CharField(default='', max_length=2048)),
                ('day_night', models.CharField(default='', max_length=8)),
                ('game_number', models.IntegerField(default=1)),
                ('inning', models.CharField(default='', max_length=16)),
                ('inning_half', models.CharField(default='', max_length=16)),
                ('srid_home_pp', models.CharField(help_text='srid of the HOME probable pitcher set before the game starts', null=True, max_length=64)),
                ('srid_home_sp', models.CharField(help_text='srid of the HOME starting pitcher', null=True, max_length=64)),
                ('srid_away_pp', models.CharField(help_text='srid of the AWAY probable pitcher set before the game starts', null=True, max_length=64)),
                ('srid_away_sp', models.CharField(help_text='srid of the AWAY starting pitcher', null=True, max_length=64)),
                ('srid_win', models.CharField(null=True, max_length=64)),
                ('srid_loss', models.CharField(null=True, max_length=64)),
                ('home_errors', models.IntegerField(default=0)),
                ('home_hits', models.IntegerField(default=0)),
                ('away_errors', models.IntegerField(default=0)),
                ('away_hits', models.IntegerField(default=0)),
                ('away_type', models.ForeignKey(related_name='mlb_gameboxscore_away_team', to='contenttypes.ContentType')),
                ('home_type', models.ForeignKey(related_name='mlb_gameboxscore_home_team', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GamePortion',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(help_text='the sportsradar global id for the game this is associate with', max_length=64)),
                ('game_id', models.PositiveIntegerField()),
                ('category', models.CharField(help_text='typically one of these: ["inning-half","quarter","period"]', default='', max_length=32)),
                ('sequence', models.IntegerField(help_text='an ordering of all GamePortions with the same srid_game', default=0)),
                ('game_type', models.ForeignKey(related_name='mlb_gameportion_sport_game', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pbp',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(help_text='the sportsradar global id for the game', max_length=64)),
                ('game_id', models.PositiveIntegerField()),
                ('game_type', models.ForeignKey(related_name='mlb_pbp_sport_game', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PbpDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pbp_id', models.PositiveIntegerField()),
                ('portion_id', models.PositiveIntegerField()),
                ('idx', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1024)),
                ('pbp_type', models.ForeignKey(related_name='mlb_pbpdescription_pbpdesc_pbp', to='contenttypes.ContentType')),
                ('portion_type', models.ForeignKey(related_name='mlb_pbpdescription_pbpdesc_portion', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', unique=True, max_length=64)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('injury_id', models.PositiveIntegerField(null=True)),
                ('srid_team', models.CharField(default='', max_length=64)),
                ('preferred_name', models.CharField(default='', max_length=64)),
                ('birthcity', models.CharField(default='', max_length=64)),
                ('birthcountry', models.CharField(default='', max_length=64)),
                ('birthdate', models.CharField(default='', max_length=64)),
                ('height', models.FloatField(help_text='inches', default=0.0)),
                ('weight', models.FloatField(help_text='lbs', default=0.0)),
                ('jersey_number', models.CharField(default='', max_length=64)),
                ('primary_position', models.CharField(default='', max_length=64)),
                ('status', models.CharField(help_text='roster status - ie: "A" means they are ON the roster. Not particularly active as in not-injured!', default='', max_length=64)),
                ('pro_debut', models.CharField(default='', max_length=64)),
                ('throw_hand', models.CharField(default='', max_length=8)),
                ('bat_hand', models.CharField(default='', max_length=8)),
                ('injury_type', models.ForeignKey(null=True, to='contenttypes.ContentType', related_name='mlb_player_players_injury')),
                ('position', models.ForeignKey(related_name='mlb_player_player_position', to='sports.Position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsHitter',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(help_text='the sportsradar global id for the game', max_length=64)),
                ('srid_player', models.CharField(help_text='the sportsradar global id for the player', max_length=64)),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('position', models.CharField(default='', max_length=16)),
                ('primary_position', models.CharField(default='', max_length=16)),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('bb', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('ktotal', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('ap', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('xbh', models.IntegerField(default=0)),
                ('game_type', models.ForeignKey(related_name='mlb_playerstatshitter_sport_game', to='contenttypes.ContentType')),
                ('player_type', models.ForeignKey(related_name='mlb_playerstatshitter_sport_player', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsPitcher',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(help_text='the sportsradar global id for the game', max_length=64)),
                ('srid_player', models.CharField(help_text='the sportsradar global id for the player', max_length=64)),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('position', models.CharField(default='', max_length=16)),
                ('primary_position', models.CharField(default='', max_length=16)),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('ip_1', models.FloatField(default=0.0)),
                ('ip_2', models.FloatField(default=0.0)),
                ('ktotal', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('loss', models.BooleanField(default=False)),
                ('qstart', models.BooleanField(default=False)),
                ('er', models.IntegerField(default=0)),
                ('r_total', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('cg', models.BooleanField(default=False)),
                ('cgso', models.BooleanField(default=False)),
                ('nono', models.BooleanField(default=False)),
                ('game_type', models.ForeignKey(related_name='mlb_playerstatspitcher_sport_game', to='contenttypes.ContentType')),
                ('player_type', models.ForeignKey(related_name='mlb_playerstatspitcher_sport_player', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=100)),
                ('season_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, auto_created=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(help_text='the sportsradar global id', unique=True, max_length=64)),
                ('srid_venue', models.CharField(help_text='the sportsradar global id', max_length=64)),
                ('name', models.CharField(help_text='the team name, without the market/city. ie: "Lakers", or "Eagles"', default='', max_length=64)),
                ('alias', models.CharField(help_text='the abbreviation for the team, ie: for Boston Celtic alias == "BOS"', default='', max_length=64)),
                ('srid_league', models.CharField(help_text='league sportsradar id', max_length=64)),
                ('srid_division', models.CharField(help_text='division sportsradar id', max_length=64)),
                ('market', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(to='mlb.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(related_name='game_awayteam', to='mlb.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(related_name='game_hometeam', to='mlb.Team'),
        ),
    ]
