# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mlb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportsradar global id', unique=True)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('srid_home', models.CharField(max_length=64, help_text='home team sportsradar global id')),
                ('srid_away', models.CharField(max_length=64, help_text='away team sportsradar global id')),
                ('title', models.CharField(null=True, max_length=128)),
                ('attendance', models.IntegerField(default=0)),
                ('day_night', models.CharField(max_length=8, default='')),
                ('game_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameBoxscore',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game', default=None, unique=True)),
                ('srid_home', models.CharField(max_length=64)),
                ('srid_away', models.CharField(max_length=64)),
                ('attendance', models.IntegerField(default=0)),
                ('coverage', models.CharField(max_length=16, default='')),
                ('status', models.CharField(max_length=64, default='')),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=256, default='')),
                ('home_scoring_json', models.CharField(max_length=2048, default='')),
                ('away_scoring_json', models.CharField(max_length=2048, default='')),
                ('day_night', models.CharField(max_length=8, default='')),
                ('game_number', models.IntegerField(default=1)),
                ('inning', models.CharField(max_length=16, default='')),
                ('inning_half', models.CharField(max_length=16, default='')),
                ('srid_home_pp', models.CharField(null=True, help_text='srid of the HOME probable pitcher set before the game starts', max_length=64)),
                ('srid_home_sp', models.CharField(null=True, help_text='srid of the HOME starting pitcher', max_length=64)),
                ('srid_away_pp', models.CharField(null=True, help_text='srid of the AWAY probable pitcher set before the game starts', max_length=64)),
                ('srid_away_sp', models.CharField(null=True, help_text='srid of the AWAY starting pitcher', max_length=64)),
                ('srid_win', models.CharField(null=True, max_length=64)),
                ('srid_loss', models.CharField(null=True, max_length=64)),
                ('home_errors', models.IntegerField(default=0)),
                ('home_hits', models.IntegerField(default=0)),
                ('away_errors', models.IntegerField(default=0)),
                ('away_hits', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportsradar global id', unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('srid_team', models.CharField(max_length=64, default='')),
                ('preferred_name', models.CharField(max_length=64, default='')),
                ('birthcity', models.CharField(max_length=64, default='')),
                ('birthcountry', models.CharField(max_length=64, default='')),
                ('birthdate', models.CharField(max_length=64, default='')),
                ('height', models.FloatField(help_text='inches', default=0.0)),
                ('weight', models.FloatField(help_text='lbs', default=0.0)),
                ('jersey_number', models.CharField(max_length=64, default='')),
                ('position', models.CharField(max_length=64, default='')),
                ('primary_position', models.CharField(max_length=64, default='')),
                ('status', models.CharField(max_length=64, help_text='roster status - ie: "A" means they are ON the roster. Not particularly active as in not-injured!', default='')),
                ('pro_debut', models.CharField(max_length=64, default='')),
                ('throw_hand', models.CharField(max_length=8, default='')),
                ('bat_hand', models.CharField(max_length=8, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsHitter',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game')),
                ('srid_player', models.CharField(max_length=64, help_text='the sportsradar global id for the player')),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('position', models.CharField(max_length=16, default='')),
                ('primary_position', models.CharField(max_length=16, default='')),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('bb', models.IntegerField(default=0)),
                ('s', models.IntegerField(default=0)),
                ('d', models.IntegerField(default=0)),
                ('t', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('rbi', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('ktotal', models.IntegerField(default=0)),
                ('ab', models.IntegerField(default=0)),
                ('ap', models.IntegerField(default=0)),
                ('lob', models.IntegerField(default=0)),
                ('xbh', models.IntegerField(default=0)),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatshitter_sport_game')),
                ('player_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatshitter_sport_player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerStatsPitcher',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid_game', models.CharField(max_length=64, help_text='the sportsradar global id for the game')),
                ('srid_player', models.CharField(max_length=64, help_text='the sportsradar global id for the player')),
                ('game_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('position', models.CharField(max_length=16, default='')),
                ('primary_position', models.CharField(max_length=16, default='')),
                ('play', models.BooleanField(default=False)),
                ('start', models.BooleanField(default=False)),
                ('ip_1', models.FloatField(default=0.0)),
                ('ip_2', models.FloatField(default=0.0)),
                ('ktotal', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('loss', models.BooleanField(default=False)),
                ('qstart', models.BooleanField(default=False)),
                ('er', models.IntegerField(default=0)),
                ('r_total', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('bb', models.IntegerField(default=0)),
                ('hbp', models.IntegerField(default=0)),
                ('cg', models.BooleanField(default=False)),
                ('cgso', models.BooleanField(default=False)),
                ('nono', models.BooleanField(default=False)),
                ('game_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatspitcher_sport_game')),
                ('player_type', models.ForeignKey(to='contenttypes.ContentType', related_name='mlb_playerstatspitcher_sport_player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('start_year', models.CharField(max_length=100)),
                ('season_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('srid', models.CharField(max_length=64, help_text='the sportsradar global id', unique=True)),
                ('srid_venue', models.CharField(max_length=64, help_text='the sportsradar global id')),
                ('name', models.CharField(max_length=64, help_text='the team name, without the market/city. ie: "Lakers", or "Eagles"', default='')),
                ('alias', models.CharField(max_length=64, help_text='the abbreviation for the team, ie: for Boston Celtic alias == "BOS"', default='')),
                ('srid_league', models.CharField(max_length=64, help_text='league sportsradar id')),
                ('srid_division', models.CharField(max_length=64, help_text='division sportsradar id')),
                ('market', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(to='mlb.Team'),
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='away',
            field=models.ForeignKey(to='mlb.Team', related_name='gameboxscore_away'),
        ),
        migrations.AddField(
            model_name='gameboxscore',
            name='home',
            field=models.ForeignKey(to='mlb.Team', related_name='gameboxscore_home'),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(to='mlb.Team', related_name='game_awayteam'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(to='mlb.Team', related_name='game_hometeam'),
        ),
    ]
