# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0012_probablepitcher_srid_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeAtBat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_updated', models.IntegerField(default=0, help_text='unix timestamp when this was originally parsed by dataden')),
                ('srid', models.CharField(help_text='sportsradar global id', max_length=64)),
                ('at_bat', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
