# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0013_realtimeatbat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeatbat',
            name='dd_updated',
            field=models.BigIntegerField(default=0, help_text='unix timestamp when this was originally parsed by dataden'),
        ),
    ]
