# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0014_auto_20160621_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='dataden parent api of feed', max_length=32)),
                ('game_srid', models.CharField(help_text='sportsradar global id', max_length=64)),
                ('at_bat', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
