# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0014_auto_20160621_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatshitter',
            name='fp_change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerstatspitcher',
            name='fp_change',
            field=models.FloatField(default=0.0),
        ),
    ]
