# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0016_auto_20160722_1507'),
        ('mlb', '0015_auto_20160727_1806'),
    ]

    operations = [
    ]
