# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0018_game_boxscore_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatshitter',
            unique_together=set([('srid_player', 'srid_game')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatspitcher',
            unique_together=set([('srid_player', 'srid_game')]),
        ),
    ]
