# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlb', '0019_auto_20161004_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'MLB Player'},
        ),
    ]
