# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models


def load_ibb_mlb_stat_point(apps, schema_editor):
    """
    Since the `ibb` stat was not accounted for, we need to add it to the StatPoint table in order
    for it to be used.
    
    :param apps: 
    :param schema_editor: 
    :return: 
    """

    # Get model classes.
    ScoreSystem = apps.get_model('scoring', 'ScoreSystem')
    StatPoint = apps.get_model('scoring', 'StatPoint')

    # Get the MLB ScoreSystem model.
    score_system = ScoreSystem.objects.get(sport='mlb')

    # Hitter
    StatPoint.objects.create(
        score_system=score_system,
        stat='ibb',
        value=3.0,
    )

    # Pitcher
    StatPoint.objects.create(
        score_system=score_system,
        stat='iwalk',
        value=-1,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('scoring', '0004_remove_statpoint_str_format'),
        ('mlb', '0022_auto_20170105_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatshitter',
            name='ibb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstatspitcher',
            name='ibb',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(load_ibb_mlb_stat_point)
    ]
