# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from rakepaid.classes import LoyaltyStatusManager
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# rakepaid.migrations.0003_loyaltystatus
def load_initial_data(apps, schema_editor):
    """
    load the initial loyalty tiers from rakepaid/classes.py LoyaltyStatusManager
    """

    #
    # get the model by name
    LoyaltyStatus = apps.get_model('rakepaid', 'LoyaltyStatus')
    for s in LoyaltyStatusManager.DEFAULT_STATUSES:
        status, created = LoyaltyStatus.objects.get_or_create( name=s.get('name'),
                                        rank=s.get('rank'),
                                        thirty_day_avg=s.get('thirty_day_avg'),
                                        multiplier=s.get('multiplier') )


class Migration(migrations.Migration):

    replaces = [('rakepaid', '0001_initial'), ('rakepaid', '0002_auto_20150731_1655'), ('rakepaid', '0003_loyaltystatus'), ('rakepaid', '0004_playertier'), ('rakepaid', '0005_auto_20150918_1539'), ('rakepaid', '0006_auto_20150918_1546')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_auto_20150408_0015'),
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakepaidBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RakepaidTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transaction.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='rakepaidtransactiondetail',
            unique_together=set([('user', 'transaction')]),
        ),
        migrations.CreateModel(
            name='LoyaltyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('rank', models.IntegerField(default=0)),
                ('thirty_day_avg', models.FloatField(default=0, help_text='the minimum required base fpp earned in the last 30 days to achieve this status')),
                ('multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RunPython(
            code=load_initial_data,
        ),
        migrations.CreateModel(
            name='PlayerTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rakepaid.LoyaltyStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='rakepaidbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rakepaidtransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='rakepaidbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='rakepaidtransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
