# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0014_auto_20161207_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft_pick',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft_round',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft_year',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, default=0.0, help_text='inches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='injury_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='injury_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhl_player_players_injury', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='srid_draft_team',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='srid_team',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(blank=True, default='', help_text='roster status - ie: "ACT" means they are ON the roster. Not particularly active as in not-injured!', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, help_text='lbs'),
        ),
    ]
