# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_squashed_0013_auto_20160719_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to='contest.Contest'),
        ),
    ]
