# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_currententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(default='', help_text='frontfacing name', max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contestpool',
            name='name',
            field=models.CharField(default='', help_text='frontfacing name', max_length=256, verbose_name='Name'),
        ),
    ]
