# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def load_initial_data(apps, schema_editor):
    """
    Loads the initial SkillLevel models.
    This function will be passed to 'migrations.RunPython' which supplies the arguments.

    :param apps:
    :param schema_editor:
    :return:
    """

    skill_levels = [
        {
            'name': 'veteran',
            'gte': 10.0,
            'enforced': True,
        },
        {
            'name': 'rookie',
            'gte': 0.0,
            'enforced': True,
        },
        {
            'name': 'all',
            'gte': 0,
            'enforced': False,
        }
    ]

    #
    # get the model by name
    SkillLevel = apps.get_model('contest', 'SkillLevel')

    for data in skill_levels:
        skill_level, created = SkillLevel.objects.get_or_create(name=data.get('name'),
                                        gte=data.get('gte'), enforced=data.get('enforced'))

class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20160705_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gte', models.FloatField(default=0.0, help_text='this SkillLevel is for buyins Greater-than-or-Equal (gte) to this value.')),
                ('enforced', models.BooleanField(default=True)),
            ],
        ),

        #
        # we want to create the SkillLevel models before we tack the
        # new fields on contestpools/contests so we can apply a non-null default
        migrations.RunPython(load_initial_data),

        migrations.AddField(
            model_name='contest',
            name='skill_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.SkillLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestpool',
            name='skill_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contest.SkillLevel'),
            preserve_default=False,
        ),
    ]
