# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20160705_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('gte', models.FloatField(default=0.0, help_text='this SkillLevel is for buyins Greater-than-or-Equal (gte) to this value.')),
                ('enforced', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='skill_level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.SkillLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestpool',
            name='skill_level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contest.SkillLevel'),
            preserve_default=False,
        ),
    ]
