# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('prize', '0001_initial'), ('prize', '0002_createticketprizestructure_generatorsettings_prizestructure_rank'), ('prize', '0003_prizestructure_buyin'), ('prize', '0004_auto_20150902_1416'), ('prize', '0005_auto_20150902_1507'), ('prize', '0006_auto_20160209_2241')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicketPrizeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ticket_value', models.FloatField(default=0.0, help_text='Enter the value of a valid ticket.', verbose_name='Ticket Value')),
                ('num_prizes', models.IntegerField(default=0, help_text='The number of tickets this prize structure should pay out.', verbose_name='The Number of Total Tickets')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyin', models.IntegerField(default=0)),
                ('first_place', models.IntegerField(default=0)),
                ('round_payouts', models.IntegerField(default=0)),
                ('payout_spots', models.IntegerField(default=0)),
                ('prize_pool', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', help_text='Use a name that will help you remember what the prize structure is for.', max_length=128)),
                ('generator', models.ForeignKey(blank=True, help_text='You do not need to specify one of these. But automatically created prize pools may be associated with a generator.', null=True, on_delete=django.db.models.deletion.CASCADE, to='prize.GeneratorSettings')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('amount_id', models.IntegerField(help_text='the id of the amount_type field')),
                ('amount_type', models.ForeignKey(help_text='MUST be a CashAmount or TicketAmount', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('prize_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='prize.PrizeStructure')),
            ],
        ),
        migrations.AlterField(
            model_name='generatorsettings',
            name='buyin',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generatorsettings',
            name='first_place',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='generatorsettings',
            name='prize_pool',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelOptions(
            name='prizestructure',
            options={'verbose_name': 'Prize Structure', 'verbose_name_plural': 'Prize Structure'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Payout Structure', 'verbose_name_plural': 'Payout Structure'},
        ),
    ]
