# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0001_squashed_0006_auto_20160209_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['rank'], 'verbose_name': 'Payout Structure', 'verbose_name_plural': 'Payout Structure'},
        ),
    ]
