# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_auto_20160819_2141'),
        ('nfl', '0011_auto_20160825_0015'),
    ]

    operations = [
    ]
