# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_auto_20160830_1435'),
        ('nfl', '0012_merge'),
    ]

    operations = [
    ]
