# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0013_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together=set([('srid_player', 'srid_game')]),
        ),
    ]
