# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 10:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ticket.models

def load_initial_data(apps, schema_editor):
    """
    create the CashAmount objects for the initial Ticket amounts

    :param apps:
    :param schema_editor:
    :return:
    """

    CashAmount          = apps.get_model('cash',  'CashAmount')

    amounts = [ x[0] for x in ticket.models.DEFAULT_TICKET_VALUES ]
    for amount in amounts:
        try:
            cash_amount = CashAmount.objects.get( amount=amount )
        except CashAmount.DoesNotExist:
            cash_amount = CashAmount()
            cash_amount.amount = amount
            cash_amount.save()


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cash.migrations.0009_auto_20151204_1204

class Migration(migrations.Migration):

    replaces = [('cash', '0001_initial'), ('cash', '0002_auto_20150422_1944'), ('cash', '0003_cashamount'), ('cash', '0004_auto_20150727_1527'), ('cash', '0005_auto_20150731_1655'), ('cash', '0006_auto_20150918_1539'), ('cash', '0007_auto_20150918_1546'), ('cash', '0008_optimalpaymentstransaction'), ('cash', '0009_auto_20151204_1204'), ('cash', '0010_auto_20160209_2241'), ('cash', '0011_auto_20160519_1922'), ('cash', '0012_paypalcreditcardtransaction_paypalsavedcardtransaction_paypaltransaction'), ('cash', '0013_vzerotransaction')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0006_require_contenttypes_0002'),
        ('transaction', '0002_auto_20150408_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCashDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCashWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BraintreeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braintree_transaction', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='admincashwithdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admincashwithdrawal_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincashdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admincashdeposit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cashtransactiondetail',
            unique_together=set([('user', 'transaction')]),
        ),
        migrations.CreateModel(
            name='CashAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cashtransactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='cashtransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cashtransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        # migrations.CreateModel(
        #     name='OptimalPaymentsTransaction',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('netbanx_transaction_id', models.CharField(help_text='netbanx id found in the payment processor account', max_length=128)),
        #         ('created', models.DateTimeField(auto_now_add=True, null=True)),
        #         ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
        #     ],
        # ),
        migrations.RunPython(
            code=load_initial_data,
        ),
        migrations.AlterModelOptions(
            name='admincashdeposit',
            options={'verbose_name': 'Admin Gift'},
        ),
        migrations.AlterModelOptions(
            name='admincashwithdrawal',
            options={'verbose_name': 'Admin Removal'},
        ),
        migrations.AlterModelOptions(
            name='cashtransactiondetail',
            options={'verbose_name': 'Cash Transaction'},
        ),
        migrations.AlterUniqueTogether(
            name='cashtransactiondetail',
            unique_together=set([]),
        ),
        # solve django migrate issue
        # migrations.RemoveField(
        #     model_name='optimalpaymentstransaction',
        #     name='transaction',
        # ),
        # migrations.DeleteModel(
        #     name='OptimalPaymentsTransaction',
        # ),
        migrations.CreateModel(
            name='PayPalCreditCardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('paypal_transaction_id', models.CharField(max_length=128)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalSavedCardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('paypal_transaction_id', models.CharField(max_length=128)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('paypal_transaction_id', models.CharField(max_length=128)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='VZeroTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_identifier', models.CharField(max_length=128)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
    ]
