# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20150408_0015'),
        ('cash', '0002_auto_20170303_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='GidxTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('merchant_transaction_id', models.CharField(help_text='The MerchantTransactionID in the GIDX dashboard', max_length=128)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
            ],
        ),
    ]
