# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20170831_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gidxtransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gidx_transaction', to='transaction.Transaction'),
        ),
    ]
