# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('replayer', '0001_initial'), ('replayer', '0002_replay_update'), ('replayer', '0003_timemachine'), ('replayer', '0004_auto_20151201_0035'), ('replayer', '0005_auto_20151201_1735'), ('replayer', '0006_auto_20151201_2046'), ('replayer', '0007_auto_20151204_0118'), ('replayer', '0008_auto_20151204_0133'), ('replayer', '0009_auto_20151204_0156'), ('replayer', '0010_auto_20151208_2310'), ('replayer', '0011_auto_20151209_1446'), ('replayer', '0012_timemachine_snapshot_datetime'), ('replayer', '0013_auto_20151209_1846'), ('replayer', '0014_auto_20151209_1846'), ('replayer', '0015_auto_20160315_1706')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('ns', models.CharField(max_length=64)),
                ('o', models.CharField(max_length=131072)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loader_task_id', models.CharField(default=None, max_length=255, null=True)),
                ('playback_task_id', models.CharField(default=None, max_length=255, null=True)),
                ('replay', models.CharField(default='', help_text='the name of the replay (a postgres dump) on s3', max_length=255)),
                ('start', models.DateTimeField(help_text='the time you want to start at in the replay. must be within the start and end of the recorded stats')),
                ('current', models.DateTimeField(blank=True, help_text='where the replay is currently', null=True)),
                ('playback_mode', models.CharField(choices=[('play-all', 'Play All'), ('play-to-target', 'Play to Target')], max_length=64)),
                ('target', models.DateTimeField(blank=True, help_text='SET THE STOP TARGET FOR PLAY-TO-TARGET mode. the time you want to start at in the replay. must be within the start and end of the recorded stats', null=True)),
                ('fill_contest_status', models.CharField(default=None, max_length=64, null=True)),
                ('fill_contests_task_id', models.CharField(default=None, max_length=255, null=True)),
                ('load_status', models.CharField(default=None, max_length=64, null=True)),
                ('playback_status', models.CharField(default=None, max_length=64, null=True)),
                ('snapshot_datetime', models.DateTimeField(blank=True, help_text='internal field for settings the time to rewind the server to when the replay dump is re-loaded.', null=True)),
            ],
        ),
    ]
