# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0011_game_boxscore_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstats',
            unique_together=set([('srid_player', 'srid_game')]),
        ),
    ]
