# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('fpp', '0001_initial'), ('fpp', '0002_auto_20150428_0122'), ('fpp', '0003_auto_20150727_1527'), ('fpp', '0004_auto_20150731_1655'), ('fpp', '0005_auto_20150918_1539'), ('fpp', '0006_auto_20150918_1546'), ('fpp', '0007_auto_20160209_2241')]

    initial = True

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_auto_20150408_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFppDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminFppWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FppBalance',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FppTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adminfppwithdraw',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminfppwithdraw_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminfppdeposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminfppdeposit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fpptransactiondetail',
            unique_together=set([('user', 'transaction')]),
        ),
        migrations.AlterField(
            model_name='fpptransactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='fpptransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fpptransactiondetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterModelOptions(
            name='adminfppdeposit',
            options={'verbose_name': 'Admin Gift'},
        ),
        migrations.AlterModelOptions(
            name='adminfppwithdraw',
            options={'verbose_name': 'Admin Removal'},
        ),
        migrations.AlterModelOptions(
            name='fppbalance',
            options={'verbose_name': 'FPP Balance'},
        ),
        migrations.AlterModelOptions(
            name='fpptransactiondetail',
            options={'verbose_name': 'FPP Transaction'},
        ),
        migrations.AlterUniqueTogether(
            name='fpptransactiondetail',
            unique_together=set([]),
        ),
    ]
