# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpp', '0001_squashed_0007_auto_20160209_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpptransactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction'),
        ),
    ]
