# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0012_salary_num_games_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='avg_fppg_for_position',
            field=models.FloatField(default=0.0, verbose_name='Past x Games Positional FPPG'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fppg',
            field=models.FloatField(default=0.0, help_text='simply: (sum of fantasy points for trailing games) / (# of trailing games)', verbose_name='Season FPPG'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fppg_pos_weighted',
            field=models.FloatField(default=0.0, verbose_name='Past x Games FPPG'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='num_games_included',
            field=models.IntegerField(default=0, verbose_name='Num Games Included'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='primary_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.RosterSpot', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='min_avg_fppg_allowed_for_avg_calc',
            field=models.FloatField(default=0.0, help_text='The minimum fppg allowed for a players stats to be used to calculate position averages.', verbose_name='Min FPPG Allowed for Avg Calc'),
        ),
    ]
