# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0013_auto_20160727_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='sal_dk',
            field=models.FloatField(blank=True, null=True, verbose_name='DK Salary'),
        ),
        migrations.AddField(
            model_name='salary',
            name='sal_fd',
            field=models.FloatField(blank=True, null=True, verbose_name='FD Salary'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='avg_fppg_for_position',
            field=models.FloatField(default=0.0, verbose_name='Avg Proj for Position'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fppg',
            field=models.FloatField(default=0.0, verbose_name='STATS Projection'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fppg_pos_weighted',
            field=models.FloatField(default=0.0, verbose_name='STATS Projection'),
        ),
    ]
