# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0014_auto_20161005_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='random_percent_adjust',
            field=models.FloatField(default=0.0, help_text='if this is non-zero, apply an additional shift to all salaries randomly chosen from [-X%, +X% ]. this will happen before the final rounding.'),
        ),
        migrations.AddField(
            model_name='salary',
            name='random_adjust_amount',
            field=models.FloatField(default=0.0, help_text='the amount of ($) salary +/- applied before final rounding.'),
        ),
    ]
