# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0015_auto_20161015_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='amount_unadjusted',
            field=models.PositiveIntegerField(default=0, verbose_name='Salary Pre-Ownership Adjustments'),
        ),
    ]
