# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0017_salary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_locked',
            field=models.BooleanField(default=False, help_text='Lock this salary until the next draftgroup is created. This prevents the salary you see from being overridden by a stats.com projection update', verbose_name='Locked'),
        ),
    ]
