# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20160601_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statpoint',
            name='str_format',
        ),
    ]
