# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_squashed_0019_gamechild_boxscore_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatschild',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
