# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20170105_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetailchild',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction'),
        ),
    ]
