# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('trulioo', '0001_initial'), ('trulioo', '0002_verification'), ('trulioo', '0003_auto_20160809_1416'), ('trulioo', '0004_auto_20160809_1427'), ('trulioo', '0005_auto_20160809_1428')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction_record', models.CharField(default='', max_length=255)),
                ('record_status', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
