# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trulioo', '0001_squashed_0005_auto_20160809_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='record_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verification',
            name='transaction_record',
            field=models.CharField(max_length=255),
        ),
    ]
