# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trulioo', '0002_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='identifier',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='verification',
            name='transaction_record',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
