# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trulioo', '0003_auto_20160809_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='match',
        ),
        migrations.AddField(
            model_name='verification',
            name='record_status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
