# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trulioo', '0004_auto_20160809_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
