# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('lobby', '0001_initial'), ('lobby', '0002_contestbanner_promotionbanner'), ('lobby', '0003_auto_20160108_1518'), ('lobby', '0004_auto_20160108_1531'), ('lobby', '0005_auto_20160108_1531')]

    initial = True

    dependencies = [
        ('contest', '0001_squashed_0013_auto_20160719_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('internal_description', models.CharField(default='', help_text='PRIVATE description of what this banner is for. should not displayed on the front end', max_length=2048)),
                ('start_time', models.DateTimeField(help_text='do not display the banner before the start time')),
                ('end_time', models.DateTimeField(help_text='all good things must come to an end. and you need to specify the time when this banner should no longer be displayed.')),
                ('image_url', models.URLField(help_text='a public link to the image for this banner', null=True)),
                ('links_to', models.URLField(help_text='if you want the banner to be clickable, then you should add a link here', null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('internal_description', models.CharField(default='', help_text='PRIVATE description of what this banner is for. should not displayed on the front end', max_length=2048)),
                ('start_time', models.DateTimeField(help_text='do not display the banner before the start time')),
                ('end_time', models.DateTimeField(help_text='all good things must come to an end. and you need to specify the time when this banner should no longer be displayed.')),
                ('image_url', models.URLField(help_text='a public link to the image for this banner', null=True)),
                ('links_to', models.URLField(help_text='if you want the banner to be clickable, then you should add a link here', null=True)),
                ('priority', models.IntegerField(default=1, help_text='1 = highest priority, 1 > 2 > 3... etc...')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='contestbanner',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='contestbanner',
            name='priority',
            field=models.IntegerField(default=1, help_text='1 = highest priority, 1 > 2 > 3... etc...'),
        ),
        migrations.AlterField(
            model_name='contestbanner',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='contestbanner',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
