# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0003_refund_contest_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Entry'),
        ),
    ]
