# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0004_auto_20170301_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Entry'),
        ),
    ]
