# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('lineup', '0001_initial'), ('lineup', '0002_lineup'), ('lineup', '0003_lineup_draftgroup'), ('lineup', '0004_auto_20150724_1301'), ('lineup', '0005_auto_20150817_1959'), ('lineup', '0006_lineup_name'), ('lineup', '0007_player_draft_group_player'), ('lineup', '0008_auto_20150321_0552')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0002_auto_20150529_0216'),
        ('draftgroup', '0012_player_game_team'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('draftgroup', '0009_player_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fantasy_points', models.FloatField(blank=True, default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('draft_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draftgroup.DraftGroup')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player_id', models.PositiveIntegerField()),
                ('idx', models.PositiveIntegerField(default=0)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lineup.Lineup')),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_player_player', to='contenttypes.ContentType')),
                ('roster_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.RosterSpot')),
                ('draft_group_player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='draftgroup.Player')),
            ],
        ),
    ]
