# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0005_auto_20160804_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalwithdraw',
            name='auth_status',
        ),
        migrations.RemoveField(
            model_name='paypalwithdraw',
            name='get_status',
        ),
        migrations.RemoveField(
            model_name='paypalwithdraw',
            name='payout_status',
        ),
        migrations.AddField(
            model_name='checkwithdraw',
            name='processed_at',
            field=models.DateTimeField(null=True, verbose_name='Proccessed At'),
        ),
        migrations.AddField(
            model_name='paypalwithdraw',
            name='paypal_payout_item',
            field=models.CharField(default='', max_length=255, verbose_name='PayPal Payout Item ID'),
        ),
        migrations.AddField(
            model_name='paypalwithdraw',
            name='paypal_transaction_status',
            field=models.CharField(default='', max_length=255, verbose_name='PayPal Transaction Status'),
        ),
        migrations.AddField(
            model_name='paypalwithdraw',
            name='processed_at',
            field=models.DateTimeField(null=True, verbose_name='Proccessed At'),
        ),
        migrations.AlterField(
            model_name='checkwithdraw',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='NetProfit @ Withdraw Time'),
        ),
        migrations.AlterField(
            model_name='checkwithdraw',
            name='status_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='NetProfit @ Withdraw Time'),
        ),
        migrations.AlterField(
            model_name='paypalwithdraw',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='NetProfit @ Withdraw Time'),
        ),
        migrations.AlterField(
            model_name='paypalwithdraw',
            name='paypal_transaction',
            field=models.CharField(default='', max_length=255, verbose_name='PayPal Transaction ID'),
        ),
        migrations.AlterField(
            model_name='paypalwithdraw',
            name='status_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='NetProfit @ Withdraw Time'),
        ),
    ]
