# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0024_auto_20160817_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupdate',
            name='source_origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gameupdate',
            name='status',
            field=models.CharField(default='na', max_length=128),
        ),
        migrations.AddField(
            model_name='gameupdate',
            name='url_origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='source_origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='status',
            field=models.CharField(default='na', max_length=128),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='url_origin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
