# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0025_auto_20160824_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerupdate',
            name='depth_chart_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='last_text',
            field=models.CharField(default='', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='player_status_confidence',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='player_status_probability',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='roster_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='roster_status_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
