# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0026_auto_20161121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerupdate',
            name='sport',
            field=models.CharField(default='nfl', max_length=4),
            preserve_default=False,
        ),
    ]
