# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0027_playerupdate_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='salary_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_group_player', to='salary.Salary', verbose_name='points to the player salary object, which has fantasy salary information'),
        ),
    ]
