# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0027_playerupdate_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerupdate',
            name='depth_chart_status',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='last_text',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='player_status_confidence',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='player_status_probability',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='roster_status',
        ),
        migrations.RemoveField(
            model_name='playerupdate',
            name='roster_status_description',
        ),
    ]
