# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0027_playerupdate_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update_id', models.CharField(max_length=128, null=True)),
                ('updated_at', models.DateTimeField()),
                ('type', models.CharField(default='', max_length=128)),
                ('value', models.CharField(default='', max_length=8192)),
                ('status', models.CharField(default='na', max_length=128)),
                ('source_origin', models.CharField(max_length=255, null=True)),
                ('url_origin', models.CharField(max_length=255, null=True)),
                ('player_srid', models.CharField(max_length=64)),
                ('player_id', models.IntegerField(default=0)),
                ('sport', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
