# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0028_playerstatus'),
        ('draftgroup', '0028_auto_20170309_1344'),
    ]

    operations = [
    ]
