# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-22 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0029_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_srid', models.CharField(max_length=64)),
                ('player_id', models.IntegerField(default=0)),
                ('sport', models.CharField(max_length=4)),
                ('status', models.CharField(default='na', max_length=128)),
            ],
        ),
    ]
