# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
