# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0030_playerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerupdate',
            name='analysis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='playerupdate',
            name='notes',
            field=models.CharField(default='', max_length=8192),
        ),
    ]
