# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-12 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0031_auto_20170411_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerupdate',
            name='headline',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
