# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 10:06
from __future__ import unicode_literals

from django.db import migrations


def change_category(apps, schema_editor):
    # Change category for past rotowire updates
    PlayerUpdate = apps.get_model('draftgroup', 'PlayerUpdate')
    for update in PlayerUpdate.objects.filter(source_origin='rotowire'):
        update.category = 'news'
        update.save()


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0032_playerupdate_headline'),
    ]

    operations = [
        migrations.RunPython(change_category),
    ]
