# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftgroup', '0033_auto_20170502_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftgroup',
            name='category',
            field=models.CharField(blank=True, help_text='currently unused - originally intended as a grouping like "Early", "Late", or "Turbo"', max_length=32, null=True),
        ),
    ]
